# Generated by Django 3.2.5 on 2021-07-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('books', 'books'), ('electronics', 'electronics'), ('home_appliances', 'home appliances'), ('equipment', 'equipment'), ('cars', 'cars'), ('other', 'other')], default='other', max_length=20),
            preserve_default=False,
        ),
    ]
