# Generated by Django 3.2.5 on 2021-08-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shoppingitem_product_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingitem',
            name='product_pk',
        ),
    ]
